-
  match: "(^/entry/(?:(?:(?P<id>[0-9]+)/?$)|(?:(?P<slug>[A-z0-9_\-.]+)/?$))?)"
  controller: "EntryController"
  method: "index"
-
  match: "(^/options/(?:(?:(?P<key>[0-9]+)/?$)))"
  controller: "SettingsController"
  method: "index"
-
  match: "(^/upload/(?P<type>[a-z]+)/(?P<slug>[A-z0-9_\-.]+)/?$)"
  controller: "UpdateController"
  method: "update"
-
  match: "(^/login/?$)"
  controller: "LoginController"
  method: "login"
-
  match: "(^/login/submit/?$)"
  controller: "LoginController"
  method: "submit"
-
  match: "(^/logout/?$)"
  controller: "LoginController"
  method: "logout"
-
  match: "(^/settings/?$)"
  controller: "SettingsController"
  method: "settings"
-
  match: "(^\/$)"
  controller: "MainController"
  method: "frontpage"
-
  match: "(/?(?P<page>.*))"
  controller: "ErrorController"
  method: "frontpage"