-
  match: "(^/entry/(?:(?:(?P<id>[0-9]+)/?$)|(?:(?P<slug>[A-z0-9_\-.]+)/?$))?)"
  controller: "EntryController"
  method: "index"
-
  match: "(^/login/$)"
  controller: "LoginController"
  method: "login"
-
  match: "(^/login/submit/$)"
  controller: "LoginController"
  method: "submit"
-
  match: "(^\/$)"
  controller: "DefaultController"
  method: "front"
-
  match: "(/?(?P<page>.*))"
  controller: "ErrorController"
  method: "front"