-
  match: "(^/entry/(?:(?:(?P<id>[0-9]+)/?$)|(?:(?P<slug>[A-z0-9_\-.]+)/?$)))"
  controller: "Output\EntryController"
  method: "index"
-
  match: "(^/upload/(?P<type>[a-z]+)/(?P<slug>[A-z0-9_\-.]+)/?$)"
  controller: "CRUD\UpdateController"
  method: "update"
-
  match: "(^/login/?$)"
  controller: "Output\LoginController"
  method: "login"
-
  match: "(^/login/submit/?$)"
  controller: "Output\LoginController"
  method: "submit"
-
  match: "(^/logout/?$)"
  controller: "Output\LoginController"
  method: "logout"
-
  match: "(^/settings/submit/?$)"
  controller: "Output\SettingsController"
  method: "saveAll"
-
  match: "(^/settings/?$)"
  controller: "Output\SettingsController"
  method: "settings"
-
  match: "(^/install/publish/?$)"
  controller: "Output\InstallController"
  method: "publish"
-
  match: "(^/install/?$)"
  controller: "Output\InstallController"
  method: "install"
-
  match: "(^/add/(?P<type>[a-z]+)/?$)"
  controller: "Output\EntryController"
  method: "create"
-
  match: "(^/edit/(?P<type>[a-z]+)/(?:(?:(?P<id>[0-9]+)/?$)|(?:(?P<slug>[A-z0-9_\-.]+)/?$))/?$)"
  controller: "Output\EntryController"
  method: "edit"
-
  match: "(^\/$)"
  controller: "Output\MainController"
  method: "frontpage"
-
  match: "(/?(?P<page>.*))"
  controller: "Output\ErrorController"
  method: "frontpage"